# Generated by Django 4.1.7 on 2023-04-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_kategoria_klient_zadanie_remove_task_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='imie',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='nazwisko',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
