# Generated by Django 4.1.7 on 2023-04-07 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_klient_imie_klient_nazwisko'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadanie',
            name='klient',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tasks.klient'),
            preserve_default=False,
        ),
    ]
