# Generated by Django 4.1.7 on 2023-04-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_wiadomosc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiadomosc',
            name='czas',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
