# Generated by Django 4.1.7 on 2023-04-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_wiadomosc_czas'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
